language:
    - objective-c

install:
    - brew install cmake
    - brew install boost --with-c++11 -ftemplate-depth=1024 -v

script:
    - mkdir _builds
    - cd _builds
    - cmake ..
    - make
    - ctest
